In [8]:
import numpy as np
a = np.array([[20,30],[40,50]])
print(np.append(a,[90,100]))

[ 20  30  40  50  90 100]


In [11]:
print(np.insert(a,[1,2],[10],axis=0))  #array,index,value

[[20 30]
 [10 10]
 [40 50]
 [10 10]]


In [16]:
print(a)
print()
print(np.delete(a,1,axis = 1))

[[20 30]
 [40 50]]

[[20]
 [40]]
