In [1]:
a = [30,40,50]
b = [5,4,3]
print(a+b)

[30, 40, 50, 5, 4, 3]


In [8]:
#Concatenate
import numpy as np
arr1 = np.array([[30,40],[50,60]])
arr2 = np.array([[5,4],[3,2]])
print(np.concatenate([arr1,arr2]))


[[30 40]
 [50 60]
 [ 5  4]
 [ 3  2]]


In [10]:
print(np.concatenate([arr1,arr2],axis = 0))

[[30 40]
 [50 60]
 [ 5  4]
 [ 3  2]]


In [12]:
print(np.hstack([arr1,arr2]))  #horizontal concatenation

[[30 40  5  4]
 [50 60  3  2]]


In [13]:
print(np.vstack([arr1,arr2]))  #vertical concatenation

[[30 40]
 [50 60]
 [ 5  4]
 [ 3  2]]


In [23]:
a = np.array([[20,40,30],[40,10,20]])
b = np.array_split(a,2)
print(b)

[array([[20, 40, 30]]), array([[40, 10, 20]])]
