In [5]:
import numpy as np

arr1 = np.array([30,40,50,60,70])
arr2 = np.array([30,20,10,20,30])
print(arr1+arr2)
print(np.add(arr1,arr2))
print(arr1-arr2)
print(arr1*arr2)
print(arr2/arr1)

[ 60  60  60  80 100]
[ 60  60  60  80 100]
[ 0 20 40 40 40]
[ 900  800  500 1200 2100]
[1.         0.5        0.2        0.33333333 0.42857143]


In [7]:
arr1 = np.array([3,4,5,6,7])
arr2 = np.array([2])
print(np.power(arr1,arr2))

[ 9 16 25 36 49]


In [8]:
arr1 = np.array([ 9, 16, 25, 36, 49])
print(np.sqrt(arr1))
print(

[3. 4. 5. 6. 7.]
